name: Reports
version: '${version}'
main: fr.silenthill99.reports.Main
api-version: 1.16
authors: [ silenthill99 ]
description: Plugin de report
commands:
  setreport:
  setclose:
  report:
  reportsend:
    permission: group.modo-stagiaire
  inter:
    permission: group.modo-stagiaire